disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string

excluded:
  - .build
  - .swiftpm
  - Tests

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 20

file_length:
  warning: 500
  error: 1000
